version: '3.1'

services:
  flask_app:
        build:
          context: .
          dockerfile: Dockerfile.flask
        env_file:
          - .env.prod
        ports:
          - "5000:5000"
        depends_on:
          - mongo
  mongo:
    image: mongo:7.0.8
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root1234!
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    # network_mode: bridge
