version: '3.1'

services:
  mongo:
    image: mongo:7.0.8
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root1234!
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    network_mode: bridge
